"""empty message

Revision ID: 305d5de3b3a1
Revises: 7fcb52695cd9
Create Date: 2021-02-07 19:38:40.230566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305d5de3b3a1'
down_revision = '7fcb52695cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
